site_name: flixOpt
site_description: Energy and Material Flow Optimization Framework
site_url: https://flixopt.github.io/flixopt/
repo_url: https://github.com/flixOpt/flixopt
repo_name: flixOpt/flixopt


nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Concepts: concepts/overview.md
  - Examples:
    - Basic Example: examples/basic.md
    - Advanced Example: examples/advanced.md
  - API Reference:
    - FlowSystem: api/flow-system.md
    - Elements:
      - Effect: api/effect.md
      - Flow: api/flow.md
      - Bus: api/bus.md
      - Components:
        - Storage: api/components/storage.md
        - LinearConverter: api/components/linear-converter.md
        - Transmission: api/components/transmission.md
        - Source: api/components/source.md
        - Sink: api/components/sink.md
        - SourceAndSink: api/components/source-and-sink.md
        - LinearConverter: api/components/linear-converter.md
        - LinearConverter Subclasses: api/components/linear-converters.md
      - Interfaces:
        - OnOffParameters: api/interfaces/on-off-parameters.md
        - InvestParameters: api/interfaces/invest-parameters.md


    - Calculation: api/calculation.md
    - Datatypes: api/datatypes.md
  - LaTeX: latex-example.md
  - Contribute: contribute.md


theme:
  name: material
  palette:
    - scheme: default  # Light mode
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate  # Dark mode
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: images/flixopt-icon.svg
  favicon: images/flixopt-icon.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - toc.follow
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - content.code.copy

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - abbr
  - md_in_html
  - footnotes
  - tables
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - table-reader
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [flixOpt]  # Package directory relative to mkdocs.yml
          options:
            group_by_category: true
            show_source: false
            show_root_heading: true
            show_object_full_path: false
            show_category_heading: true
            show_if_no_docstring: true
            show_signature: true
            members_order: source
            heading_level: 2
            show_submodules: true
            docstring_style: numpy
            show_signature_annotations: true
            separate_signature: true
            filters: ["!^_[^_]", "^__init__"]  # Exclude private methods but include __init__
            docstring_section_style: table
            show_bases: true
            show_docstring_attributes: false  # Exclude attributes
            merge_init_into_class: true  # Merge __init__ docs into class docs
            infer_type_annotations: true

extra_javascript:
  - javascripts/mathjax.js  # Custom MathJax 3 CDN Configuration
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js  #MathJax 3 CDN
  - https://polyfill.io/v3/polyfill.min.js?features=es6  #Support for older browsers

watch:
  - flixOpt