name: 🚀 Feature Request
description: Suggest a new feature for flixopt
title: "[FEATURE] "
labels: ["type: feature"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: What feature would you like to see?
      description: A clear description of the feature you're requesting
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Describe your specific use case and how this feature would help
      placeholder: "I want to model... so that I can..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you envision this feature working?

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds you've considered